sudo: required
services:
  - docker

before_install:
  - docker build -t huseyinkervan/react -f Dockerfile.dev .

script:
  - docker run -e CI=true huseyinkervan/react npm run test  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "myreact-project"
  env: "MyreactProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-129028259635"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
